package config

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

// buildTargets are the directories Soroban toolchains write release WASM to,
// newest first. Current Rust targets wasm32v1-none; older toolchains used
// wasm32-unknown-unknown. When a contract appears under both, the first wins.
var buildTargets = []string{
	"target/wasm32v1-none/release",
	"target/wasm32-unknown-unknown/release",
}

// optimizedSuffix is what `stellar contract optimize` appends. An optimized
// build is smaller and cheaper to upload, so it is preferred when present.
const optimizedSuffix = ".optimized.wasm"

// placeholderAlias is used when no built contract is found, so the scaffold
// still validates and shows the shape to fill in.
const placeholderAlias = "my_contract"

// FoundContract is a compiled contract discovered by Scaffold.
type FoundContract struct {
	Alias string
	// Wasm is relative to the scanned directory, with forward slashes, so the
	// generated file works on any platform.
	Wasm string
}

// DiscoverContracts lists the release WASM artifacts under dir's Soroban
// build directories, one per contract, sorted by alias.
func DiscoverContracts(dir string) ([]FoundContract, error) {
	byAlias := map[string]FoundContract{}

	for _, target := range buildTargets {
		matches, err := filepath.Glob(filepath.Join(dir, filepath.FromSlash(target), "*.wasm"))
		if err != nil {
			return nil, err
		}
		sort.Strings(matches)

		inTarget := map[string]FoundContract{}
		for _, m := range matches {
			base := filepath.Base(m)
			alias := strings.TrimSuffix(strings.TrimSuffix(base, optimizedSuffix), ".wasm")
			found := FoundContract{Alias: alias, Wasm: "./" + target + "/" + base}

			// Within one target, an optimized build beats the plain one.
			if prev, ok := inTarget[alias]; ok && strings.HasSuffix(prev.Wasm, optimizedSuffix) {
				continue
			}
			inTarget[alias] = found
		}
		for alias, found := range inTarget {
			if _, ok := byAlias[alias]; !ok {
				byAlias[alias] = found
			}
		}
	}

	out := make([]FoundContract, 0, len(byAlias))
	for _, f := range byAlias {
		out = append(out, f)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Alias < out[j].Alias })
	return out, nil
}

var plainYAMLKey = regexp.MustCompile(`^[A-Za-z0-9_-]+$`)

// Scaffold renders a starter soroforge.yaml for the contracts found. With
// none, it declares a placeholder, so the file still loads and validates.
// The output is meant to be read and edited, so it carries comments rather
// than being a bare marshal.
func Scaffold(found []FoundContract) []byte {
	var b strings.Builder

	b.WriteString(`# SoroForge project configuration, generated by ` + "`soroforge init`" + `.
#
# This file is shareable and belongs in version control. Secrets never go
# here: the deployer key and DATABASE_URL come from the environment.

version: 1
default_network: testnet

networks:
  testnet:
    rpc_url: https://soroban-testnet.stellar.org
    passphrase: "Test SDF Network ; September 2015"
    # Register every confirmed deploy with a SoroVault registry:
    # sorovault_url: http://localhost:8080

  # There is no public SDF-hosted mainnet RPC; point this at a provider you
  # trust before uncommenting.
  # mainnet:
  #   rpc_url: https://your-mainnet-rpc.example.com
  #   passphrase: "Public Global Stellar Network ; September 2015"

contracts:
`)

	if len(found) == 0 {
		b.WriteString(`  # No built contracts were found under target/. Build one with
  # ` + "`stellar contract build`" + `, then point wasm at it.
  ` + placeholderAlias + `:
    wasm: ./target/wasm32v1-none/release/` + placeholderAlias + `.wasm
`)
	}
	for _, f := range found {
		key := f.Alias
		if !plainYAMLKey.MatchString(key) {
			key = strconv.Quote(key)
		}
		fmt.Fprintf(&b, "  %s:\n    wasm: %s\n", key, strconv.Quote(f.Wasm))
	}

	b.WriteString(`
  # Per-contract options:
  #   constructor_args: [{type: u32, value: 7}]
  #   upgrade_fn: upgrade        # the contract's own upgrade entrypoint
  #   salt: "<32-byte hex>"      # for a reproducible contract address
`)
	return []byte(b.String())
}

// WriteScaffold discovers contracts under dir and writes a starter config to
// path. It refuses to replace an existing file unless force is set.
func WriteScaffold(dir, path string, force bool) ([]FoundContract, error) {
	found, err := DiscoverContracts(dir)
	if err != nil {
		return nil, err
	}

	flag := os.O_WRONLY | os.O_CREATE | os.O_EXCL
	if force {
		flag = os.O_WRONLY | os.O_CREATE | os.O_TRUNC
	}
	f, err := os.OpenFile(path, flag, 0o644)
	if err != nil {
		if os.IsExist(err) {
			return nil, fmt.Errorf("%s already exists; pass --force to replace it", path)
		}
		return nil, err
	}
	if _, err := f.Write(Scaffold(found)); err != nil {
		f.Close()
		return nil, err
	}
	return found, f.Close()
}
